// 「全部收起 / 全部展开」的**选区作用域**与「折叠选区」的六档结果
// （`docs/inventory/verdict-folding.md` §G 里 `BaseFoldingHandler` / `CollapseAllRegionsAction` /
// `ExpandAllRegionsAction` 三行共同点名的「缺 `getFoldRegionsForSelection`」，
// 以及 `CollapseSelectionHandler` 行点名的「缺 `:44` 的提示」）。
//
// 上游坐标：
//   · `platform/foldings/src/com/intellij/codeInsight/folding/impl/actions/BaseFoldingHandler.java:43-58`
//     —— 有选区时取「与选区搭界」（`getRegionsOverlappingWith`，`:50-51`）**且**
//     「整条落在选区里」（`selectionRange.contains(region)`，`:51`）的那些区间；一条都没有就退回全集
//     （`:56` 的 `getAllFoldRegions()`）。
//   · `CollapseAllRegionsAction.java:31` 的目标集合就是它（`ExpandAllRegionsAction` 同一处调用）。
//   · `CollapseSelectionHandler.java:24-90` 的六个分支：移除手工区间（`:37-41`）/
//     不许移除自动生成的（`:42-45`，弹提示）/ 重叠确认框默认「取消」（`:49-58`）/
//     折起选区（`:63-69`）/ 无选区切换光标处最内层（`:75-87`）/ 什么都没做。
//     提示文案 = `CodeInsightBundle.properties:269`（`collapse.selection.existing.autogenerated.region`），
//     中文取 `localization-zh.jar` 的 `messages/CodeInsightBundle.properties:97`。
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { codeFolding, foldEffect, foldedRanges } from '@codemirror/language'
import { EditorState } from '@codemirror/state'
import { CANNOT_REMOVE_AUTOGENERATED_REGION, foldSelectionOutcome, foldingRanges, lspFoldService, selectionScoped,
  setFoldingRanges } from '../src/editorFolding.ts'
import { editingCommands } from '../src/editorCommands.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const read = relative => readFileSync(join(root, relative), 'utf8')

// 11 行、每行 1 个字符；偏移一律从文档算，不手数。
const DOC = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'].join('\n')
const RANGES = [
  { startLine: 0, endLine: 2 },   // 第 1–3 行
  { startLine: 4, endLine: 6 },   // 第 5–7 行
  { startLine: 8, endLine: 10 },  // 第 9–11 行
]

const base = EditorState.create({ doc: DOC, extensions: [codeFolding(), foldingRanges, lspFoldService] })
  .update({ effects: setFoldingRanges.of(RANGES) }).state
const area = (fromLine, toLine) => [base.doc.line(fromLine).from, base.doc.line(toLine).to]
const SPAN_1 = area(1, 3)
const SPAN_2 = area(5, 7)
const SPAN_3 = area(9, 11)
const rangeOf = ([from, to]) => ({ from, to })

const withSelection = (from, to = from) => base.update({ selection: { anchor: from, head: to } }).state
/** foldSelectionOutcome 收的是 view（EditorView 在这里只被按 {state, dispatch} 用）。 */
const viewOf = state => ({ state, dispatch: () => {} })

/** 用一个假 view 跑命令（EditorView 在这里只被按 `{state, dispatch}` 用）。 */
function run(command, initial) {
  let after = initial
  const handled = command({ state: initial, dispatch: spec => { after = initial.update(spec).state } })
  return { handled, after }
}

const spans = state => {
  const out = []
  for (const iterator = foldedRanges(state).iter(); iterator.value; iterator.next()) out.push([iterator.from, iterator.to])
  return out
}

test('选区作用域：搭界且整条在里面才算，否则 null（= 退回全集）', () => {
  const areas = [{ from: 0, to: 10 }, { from: 20, to: 30 }, { from: 40, to: 50 }]
  assert.deepEqual(selectionScoped(areas, 20, 30), [areas[1]], '选区正好等于中间那条')
  assert.equal(selectionScoped(areas, 15, 25), null, '只搭一头：`contains(region)` 那条不过 ⇒ 空 ⇒ 全集')
  assert.equal(selectionScoped(areas, 25, 25), null, '空选区')
  assert.equal(selectionScoped(areas, 30, 20), null, '反向选区')
  assert.deepEqual(selectionScoped(areas, 0, 50), areas, '选区套住全部 ⇒ 全在作用域里')
  assert.deepEqual(selectionScoped(areas, 5, 45), [areas[1]], '头尾那两条只搭界、没被完整框住 ⇒ 不算')
})

test('全部收起：有选区时只折选区里那几条', () => {
  const { handled, after } = run(editingCommands.foldAll, withSelection(SPAN_2[0], SPAN_2[1]))
  assert.equal(handled, true)
  assert.deepEqual(spans(after), [SPAN_2], '只折第 5–7 行那一条，其余两条保持展开')
})

test('全部收起：选区里一条完整区间都没有就退回整篇', () => {
  // 选区跨在第 4–5 行：与第 5–7 行那条搭界但没完整框住它，别条也不在内 ⇒ 上游那句
  // `getAllFoldRegions()` 的兜底（`BaseFoldingHandler.java:56`）。
  const straddling = area(4, 5)
  const { handled, after } = run(editingCommands.foldAll, withSelection(straddling[0], straddling[1]))
  assert.equal(handled, true)
  assert.deepEqual(spans(after), [SPAN_1, SPAN_2, SPAN_3])
  // 只有光标（没有选区）时同样整篇。
  assert.deepEqual(spans(run(editingCommands.foldAll, withSelection(0)).after), [SPAN_1, SPAN_2, SPAN_3])
})

test('全部展开：作用域同样只看选区里那几条', () => {
  const foldedAll = run(editingCommands.foldAll, withSelection(0)).after
  const scoped = foldedAll.update({ selection: { anchor: SPAN_2[0], head: SPAN_2[1] } }).state
  const { handled, after } = run(editingCommands.unfoldAll, scoped)
  assert.equal(handled, true)
  assert.deepEqual(spans(after), [SPAN_1, SPAN_3], '只有选区里那条展开了')
  // 没有选区 → 整篇展开。
  assert.deepEqual(spans(run(editingCommands.unfoldAll, after.update({ selection: { anchor: SPAN_2[0] } }).state).after), [])
})

test('折叠选区：六个分支各自报结果', () => {
  const straddling = rangeOf(area(4, 5))
  // 折起选区（`:63-69`）。
  assert.equal(foldSelectionOutcome(viewOf(withSelection(straddling.from, straddling.to))), 'collapsed')
  // 正好等于一条**自动生成**的区间 → 不许移除（`:42-45`），并把这一档报给宿主弹提示。
  const foldedOne = run(editingCommands.foldAll, withSelection(SPAN_2[0], SPAN_2[1])).after
  const onAuto = foldedOne.update({ selection: { anchor: SPAN_2[0], head: SPAN_2[1] } }).state
  assert.equal(foldSelectionOutcome(viewOf(onAuto)), 'autogenerated')
  // 手工折的那条（不在自动生成候选里）→ 移除（`:37-41`）。
  const manual = base.update({ effects: foldEffect.of(straddling) }).state
  const onManual = manual.update({ selection: { anchor: straddling.from, head: straddling.to } }).state
  assert.equal(foldSelectionOutcome(viewOf(onManual)), 'removed')
  // 与别的区间只搭一头 → 重叠那一档（上游弹确认框且默认「取消」，本仓不动）。
  const foldedFirst = base.update({ effects: foldEffect.of(rangeOf(SPAN_1)) }).state
  const onOverlap = foldedFirst.update({ selection: { anchor: SPAN_1[1] - 1, head: SPAN_2[0] } }).state
  assert.equal(foldSelectionOutcome(viewOf(onOverlap)), 'overlapping')
  // 没有选区 → 切换光标处最内层（`:75-87`）；那里什么都没有 → `nothing`。
  const onCaret = foldedOne.update({ selection: { anchor: base.doc.line(6).from } }).state
  assert.equal(foldSelectionOutcome(viewOf(onCaret)), 'toggled')
  const nowhere = base.update({ selection: { anchor: base.doc.line(8).from } }).state
  assert.equal(foldSelectionOutcome(viewOf(nowhere)), 'nothing')
})

test('命令层只对「做了事」的两档返回 true，提示文案照中文包', () => {
  assert.equal(CANNOT_REMOVE_AUTOGENERATED_REGION, '无法移除自动生成的折叠区域')
  const foldedOne = run(editingCommands.foldAll, withSelection(SPAN_2[0], SPAN_2[1])).after
  const onFolded = foldedOne.update({ selection: { anchor: SPAN_2[0], head: SPAN_2[1] } }).state
  assert.equal(editingCommands['fold.selection']({ state: onFolded, dispatch: () => {} }), false,
    '不许移除自动生成的区间 ⇒ 与改动前一样返回 false（提示由宿主按 outcome 弹）')
  const folding = read('src/editorFolding.ts')
  assert.match(folding, /export const toggleFoldSelection: Command = view => \{\n {2}const outcome = foldSelectionOutcome\(view\)/,
    '命令只问一次结果，规则不留第二份')
  const commands = read('src/editorCommands.ts')
  assert.match(commands, /foldAll: foldAllCommand, unfoldAll: unfoldAllCommand/, '整族走本仓那两条（带选区作用域）')
  assert.ok(!/from '@codemirror\/language'/.test(commands), 'CodeMirror 的整篇 foldAll 不再是命令表的内容')
})
