// exec/sm-runner / exec/testframework：导入历史测试结果的判据。
// 上游对照：platform/smRunner/.../history/ImportedTestContentHandler.java:41-129、
// java/execution/impl/.../AntTestContentHandler.java:29-156、
// .../history/actions/{ImportTestsFromFileAction,ImportTestsGroup,AbstractImportTestsAction,ImportTestsFromHistoryAction}.java、
// platform/smRunner/resources/messages/SmRunnerBundle.properties:39-44。
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import {
  IMPORT_HISTORY_SIZE_KEY, IMPORT_TESTS_NAME, historyPresentableText, importedEventLines, importedFailedNames, importedHistorySize,
  importedSessionList, importTestResults, recordImportedSession, rootElementName,
} from '../src/testImport.ts'
import { formatTestEvent } from '../src/testEventChannel.ts'

const IDEA_XML = [
  '<testrun name="mvn test" footerText="Generated by TaoCode" duration="4200">',
  '  <count name="total" value="2"/><count name="passed" value="1"/><count name="failed" value="1"/>',
  '  <suite name="MathTest" location="java:suite://com.foo.MathTest" metainfo="3:1">',
  '    <test name="adds" status="failed" duration="12" location="java:test://com.foo.MathTest/adds">',
  '      <output type="stdout">running adds</output>',
  '      <diff expected="4" actual="5"/>',
  '      <output type="stderr">expected:&lt;4&gt; but was:&lt;5&gt;</output>',
  '    </test>',
  '    <test name="subtracts" status="passed" duration="3"/>',
  '  </suite>',
  '</testrun>',
].join('\n')

const ANT_XML = [
  '<testsuites tests="2" failures="1">',
  '  <testsuite name="MathTest" package="com.foo" tests="2">',
  '    <testcase name="adds" classname="com.foo.MathTest" time="0.012"><failure message="boom">expected 4</failure></testcase>',
  '    <testcase name="slow" classname="com.foo.MathTest" time="0"><skipped/></testcase>',
  '    <system-out>whole suite stdout</system-out>',
  '  </testsuite>',
  '</testsuites>',
].join('\n')

test('认格式只看根元素（上游 AntTestContentHandler:29-43 的判据）', () => {
  assert.equal(rootElementName(IDEA_XML), 'testrun')
  assert.equal(rootElementName(ANT_XML), 'testsuites')
  const unknown = importTestResults('<report><counter/></report>')
  assert.equal(unknown.format, null)
  assert.match(unknown.error, /不是测试结果 XML/)
  assert.deepEqual(unknown.events, [])            // 认不出就什么都不产出，不臆造结果
})

test('IDEA 导出格式：suite/test/output/diff 全部转成结构化事件', () => {
  const result = importTestResults(IDEA_XML)
  assert.equal(result.format, 'idea')
  assert.equal(result.error, null)
  const kinds = result.events.map(event => event.kind)
  assert.deepEqual(kinds, ['suiteStarted', 'testStarted', 'testOutput', 'testFailed', 'testFinished',
    'testStarted', 'testFinished', 'suiteFinished'])
  assert.equal(result.root?.name, 'mvn test')     // 上游 :76-78 的 onRootPresentationAdded
})

test('失败事件带上断言两侧与 stderr 文本；结束事件无论状态都要有（上游 :100-117）', () => {
  const result = importTestResults(IDEA_XML)
  const failed = result.events.find(event => event.kind === 'testFailed')
  assert.equal(failed?.expected, '4')
  assert.equal(failed?.actual, '5')
  assert.match(failed?.details ?? '', /expected:<4> but was:<5>/)   // XML 实体还原
  const finished = result.events.filter(event => event.kind === 'testFinished')
  assert.deepEqual(finished.map(event => event.durationMs), [12, 3])
})

test('ant 格式：位置写成上游的 java:suite:// 与 java:test://（:87-88/:98-101），time 秒折算成毫秒', () => {
  const result = importTestResults(ANT_XML)
  assert.equal(result.format, 'ant')
  const suite = result.events.find(event => event.kind === 'suiteStarted')
  assert.equal(suite.locationHint, 'java:suite://com.foo.MathTest')
  const started = result.events.find(event => event.kind === 'testStarted')
  assert.equal(started.locationHint, 'java:test://com.foo.MathTest/adds')
  const finished = result.events.find(event => event.kind === 'testFinished')
  assert.equal(finished.durationMs, 12)           // 0.012 秒 → 12 ms（上游 :143）
  const skipped = result.events.find(event => event.kind === 'testIgnored')
  assert.equal(skipped?.name, 'slow')
  const output = result.events.find(event => event.kind === 'testOutput')
  assert.equal(output?.output, 'whole suite stdout')
})

test('duration 缺失写 -1 语义（本仓省掉字段）；解析失败也退 -1（上游 :113/:141-147）', () => {
  const result = importTestResults('<testrun><test name="a" status="passed"/></testrun>')
  assert.equal(result.events.find(event => event.kind === 'testFinished')?.durationMs, undefined)
})

test('认不出的状态不猜：`<flaky/>` 既不算失败也不算忽略（上游只在映射到的四种状态里分流）', () => {
  const result = importTestResults('<testsuites><testsuite name="S"><testcase name="a"><flaky/></testcase></testsuite></testsuites>')
  assert.equal(result.error, null)
  assert.deepEqual(result.events.map(event => event.kind), ['suiteStarted', 'testStarted', 'testFinished', 'suiteFinished'])
})

test('ant 的 `<failure>` 文本进失败详情（上游 :125-127 每次 endElement 都清文本，那段其实被丢掉）', () => {
  const result = importTestResults(ANT_XML)
  const failed = result.events.find(event => event.kind === 'testFailed')
  assert.equal(failed?.details, 'expected 4')
})

test('事件行喂得进现成通道（同一份处理器，两种来源）', () => {
  const lines = importedEventLines(importTestResults(IDEA_XML).events, formatTestEvent)
  assert.ok(lines.length >= 4)
  assert.match(lines[0], /^##taocode\[/)
})

test('历史条数：默认 10、坏值退 10、下限 0（AbstractImportTestsAction:87-92）', () => {
  assert.equal(importedHistorySize(null), 10)
  assert.equal(importedHistorySize('abc'), 10)
  assert.equal(importedHistorySize('-3'), 0)
  assert.equal(importedHistorySize('4'), 4)
  assert.equal(IMPORT_HISTORY_SIZE_KEY, 'test_history_size')
})

test('历史列表去重、新的在前、按上限裁（ImportTestsGroup:44-60）', () => {
  const store = new Map()
  const storage = { getItem: k => (store.has(k) ? store.get(k) : null), setItem: (k, v) => store.set(k, v) }
  recordImportedSession(storage, 'a - 2026.10.01 at 08h30m12s.xml', 10)
  recordImportedSession(storage, 'b.xml', 10)
  recordImportedSession(storage, 'a - 2026.10.01 at 08h30m12s.xml', 10)   // 重复导入不重复列
  assert.deepEqual(importedSessionList(storage, 10), ['a - 2026.10.01 at 08h30m12s.xml', 'b.xml'])
  assert.deepEqual(importedSessionList(storage, 1), ['a - 2026.10.01 at 08h30m12s.xml'])
})

test('历史项显示名：`名 - 时间戳` 折成「配置名 (时间戳)」，认不动原样（ImportTestsFromHistoryAction:39-53）', () => {
  assert.equal(historyPresentableText('MathTest - 2026.10.01 at 08h30m12s.xml', 'mvn test'), 'mvn test (2026.10.01 08:30:12)')
  assert.equal(historyPresentableText('MathTest - 乱写的.xml'), 'MathTest - 乱写的')
  assert.equal(historyPresentableText('plain.xml'), 'plain')
})

test('动作文案取自上游 bundle（ImportTestsFromFileAction:21 + SmRunnerBundle.properties:42）', () => {
  assert.equal(IMPORT_TESTS_NAME, 'Import Tests from File…')
})

test('接线：面板有真的导入入口并读文件（不是死模块）', () => {
  const source = readFileSync(new URL('../src/components/TestRunnerPanel.vue', import.meta.url), 'utf8')
  assert.match(source, /from '\.\.\/testImport'/, '面板没有引用导入模块')
  assert.match(source, /dialog\.pickFile/, '面板没有走系统文件选择框')
  assert.match(source, /IMPORT_TESTS_NAME/, '面板没有用上游的动作文案')
})

test('导入会话里失败的用例能重跑（ImportedTestRunnableState:67-78 给导入结果挂 rerun action）', () => {
  const xml = `<testrun name="MathTest" footerText="x">
  <suite name="MathTest" status="failed">
    <test name="adds" status="passed" duration="12"/>
    <test name="divides" status="failed" duration="3"/>
    <test name="divides" status="failed"/>
    <test name="boom" status="failed"/>
  </suite>
</testrun>`
  const imported = importTestResults(xml)
  assert.equal(imported.error, null)
  assert.deepEqual(importedFailedNames(imported.events), ['divides', 'boom'], '去重保序，只取失败')
  assert.deepEqual(importedFailedNames([]), [])
  const source = readFileSync(new URL('../src/components/TestRunnerPanel.vue', import.meta.url), 'utf8')
  assert.match(source, /importedFailedNames\(imported\.events\)/, '面板要从导入的事件里抽失败名')
  assert.match(source, /rerunImportedFailures/, '面板要有重跑入口')
  assert.match(source, /importedFailures\.value\)/, '失败名交给同一份 rerunCommand 拼命令')
})
