// exec/testframework：**测试结果 XML 导出**（上游 `platform/testRunner` 的
// `export/TestResultsXmlFormatter` + `ExportTestResultsAction` / `ExportTestResultsConfiguration`）。
//
// 上游依据（`platform/testRunner/src/com/intellij/execution/testframework/export/TestResultsXmlFormatter.java`）：
//   · `:38-65` 元素与属性名：根 `<testrun>`，树节点 `<suite>` / `<test>`，计数 `<count name value>`，
//     节点属性 `name` / `status` / `duration` / `locationUrl` / `metainfo` / `isConfig`，
//     文本 `<output type="stdout|stderr">`，断言差异 `<diff expected actual>`；
//     状态串 `passed` / `failed` / `error` / `ignored` / `skipped`（:58-62）；
//   · `:97-107` 计数：只数**叶子**，`total` 排第一（比较器 `:98-100` 把 total 顶到最前）；
//   · `:109-118` `<testrun>` 的属性：`name`（运行配置名）、`footerText`
//     （`ExecutionBundle.properties:343` = `Generated by {0} on {1}`）、`duration`；
//   · `:191-234` `processNode`：叶子自己开 `<test>` 并写输出；非叶子要**先有子节点才开元素**
//     （`:224-227` 的 `started` 短路 —— 空 suite 不产出空标签），并且 `hidePassedConfig` 时
//     跳过通过的 config 节点（`:219-223`）；
//   · `:236-335` 输出：按内容类型分段（`stdout` / `stderr`，`:333-335`），文本里的 `\u0000`
//     去掉（`:328-331`），差异写成 `<diff expected= actual=>`（`:268-280`）。
//
// 本仓的等价物：`formatTestResults` —— 纯函数，输入是本仓的测试树 + 失败详情，输出与上游同形的
// XML 文本。消费点：`src/components/TestRunnerPanel.vue` 的「导出 XML」（复制到剪贴板），
// 判据 `tests/test-results-xml.test.mjs`。
import type { TestTreeNode } from './testTree.ts'

/** 上游的状态串（`TestResultsXmlFormatter.java:58-62`）。 */
export const STATUS_PASSED = 'passed'
export const STATUS_FAILED = 'failed'
export const STATUS_SKIPPED = 'skipped'

export interface TestResultExport {
  /** `<testrun name>` —— 运行配置名（本仓传基础命令）。 */
  runName: string
  /** 逐个结果节点的详情：失败文本（进 `<output>`）、断言两侧（进 `<diff>`）。 */
  details?: ReadonlyMap<string, { text?: string; expected?: string | null; actual?: string | null }>
  /** `footerText` 的 {0}（产品名）。 */
  productName?: string
  /** `footerText` 的 {1}（时间戳文本）。 */
  timestamp?: string
}

function escapeXml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/\u0000/g, '')
}

function statusOf(node: TestTreeNode): string {
  if (node.outcome === 'failed') return STATUS_FAILED
  if (node.outcome === 'skipped') return STATUS_SKIPPED
  return STATUS_PASSED
}

function countLeaves(nodes: readonly TestTreeNode[]): Map<string, number> {
  const counts = new Map<string, number>()
  const add = (key: string) => counts.set(key, (counts.get(key) ?? 0) + 1)
  const walk = (list: readonly TestTreeNode[]) => {
    for (const node of list) {
      if (node.kind === 'test') add(statusOf(node))
      walk(node.children)
    }
  }
  walk(nodes)
  return counts
}

function attributes(pairs: readonly (readonly [string, string | number | null])[]): string {
  return pairs.filter(pair => pair[1] !== null && pair[1] !== '')
    .map(([key, value]) => ` ${key}="${escapeXml(String(value))}"`).join('')
}

/**
 * 测试树 → IDEA 导出格式的 XML。`total` 计数按上游的比较器排在最前（`:98-100`）。
 */
export function formatTestResults(nodes: readonly TestTreeNode[], options: TestResultExport): string {
  const counts = countLeaves(nodes)
  const lines: string[] = ['<?xml version="1.0" encoding="UTF-8"?>']
  const duration = nodes.reduce((sum, node) => sum + node.durationMs, 0)
  const footer = `Generated by ${options.productName ?? 'TaoCode'} on ${options.timestamp ?? ''}`
  lines.push(`<testrun${attributes([['name', options.runName], ['footerText', footer],
                                    ['duration', duration ? Math.round(duration) : null]])}>`)
  for (const [name, value] of [...counts].sort((a, b) => (a[0] === 'total' ? -1 : b[0] === 'total' ? 1 : a[0].localeCompare(b[0])))) {
    lines.push(`  <count${attributes([['name', name], ['value', value]])}/>`)
  }
  if (counts.size) lines.push(`  <count${attributes([['name', 'total'], ['value', totalOf(counts)]])}/>`)

  const writeNode = (node: TestTreeNode, depth: number): void => {
    const pad = '  '.repeat(depth)
    const element = node.kind === 'test' ? 'test' : 'suite'
    const head = `${pad}<${element}${attributes([
      ['name', node.name], ['status', statusOf(node)],
      ['duration', node.durationMs ? Math.round(node.durationMs) : null],
      ['locationUrl', node.location], ['metainfo', node.running ? 'running' : null],
    ])}`
    if (node.kind === 'test') {
      const detail = options.details?.get(node.id)
      const body: string[] = []
      if (detail?.expected !== undefined && detail.expected !== null && detail.actual !== undefined && detail.actual !== null)
        body.push(`${pad}  <diff${attributes([['expected', detail.expected], ['actual', detail.actual]])}/>`)
      if (detail?.text) body.push(`${pad}  <output type="stderr">${escapeXml(detail.text)}</output>`)
      lines.push(body.length ? `${head}>` : `${head}/>`, ...body, `${pad}</${element}>`)
      return
    }
    // 上游 `:224-227`：非叶子先看有没有子节点，空 suite 不产出空标签。
    if (!node.children.length) { lines.push(`${head}/>`); return }
    lines.push(`${head}>`)
    for (const child of node.children) writeNode(child, depth + 1)
    lines.push(`${pad}</${element}>`)
  }
  for (const node of nodes) writeNode(node, 1)
  lines.push('</testrun>')
  return lines.join('\n')
}

function totalOf(counts: ReadonlyMap<string, number>): number {
  let total = 0
  for (const [name, value] of counts) if (name !== 'total') total += value
  return total
}
